sudo: required
dist: trusty
group: edge
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
services:
- docker
install:
- echo "install nothing!"
script:
- echo "no tests!"
- "./mvnw clean install -B -V"
- bash <(curl -s https://codecov.io/bash)
after_success:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export CI_TEST=ystal/ci-test
- echo  "TAG = " $CI_TEST:$COMMIT
- docker build -t $CI_TEST:$COMMIT .
- docker tag $CI_TEST:$COMMIT $CI_TEST:$TAG
- docker push $CI_TEST
before_install:
- openssl aes-256-cbc -K $encrypted_dc32aa125b8c_key -iv $encrypted_dc32aa125b8c_iv
  -in digital_ocean_rsa.enc -out ./digital_ocean_rsa -d
- chmod +x ./mvnw
- chmod +x ./deploy.sh
notifications:
  email:
  - ystal@mail.ru
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./digital_ocean_rsa
    root@159.203.94.228 './deploy.sh'
  on:
    branch: master
